# Author: Marc Aldrich
#
# Date Last Modified: 2020 July 28
# Date Created: 2020 July 28
# Summary: Docker-compose file to deploy the PowerController services
# Example to bring up image: `docker run gobot-helloworld`
version: "3"
services:
  hardware_controller:
    privileged: true
    image: hub.foundries.io/tech-farm-af/powercontroller:latest
    restart: always
    ports:
      - "2080:2080"
    devices:
      - "/dev:/dev"
      - "/sys:/sys"