# Author: Marc Aldrich
#
# Date Last Modified: 2020 July 27
# Date Created: 2020 July 27
# Summary: Docker-compose file to deploy the PowerController services
# Example to bring up image: `docker run gobot-helloworld`
version: "3"
services:
  app:
    image: hub.foundries.io/tech-farm-af/powercontroller:latest